name       : tumbler
version    : 4.18.1
release    : 19
source     :
    - https://archive.xfce.org/src/xfce/tumbler/4.18/tumbler-4.18.1.tar.bz2 : ff61981a9c0af5fec768d4f1552bd63948a64b2f4db1c2e3d93c31c19dc563a0
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.library
summary    : D-Bus service for applications to request thumbnails
description: |
    The Tumbler package contains a D-Bus thumbnailing service based on the thumbnail management D-Bus specification. This is useful for generating thumbnail images of files.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libgsf-1)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxfce4util-1.0)
    - pkgconfig(poppler-glib)
setup      : |
    %configure \
        --disable-static \
        --disable-debug \
        --disable-gstreamer-thumbnailer
build      : |
    %make
install    : |
    %make_install
