name       : tumbler
version    : 0.1.31
release    : 2
source     :
    - http://archive.xfce.org/src/xfce/tumbler/0.1/tumbler-0.1.31.tar.bz2 : d0fd329273ff6ac98885eade4c3d8c87a4dd0816f713646130808bfa90b87173
license    : 
    - GPL-2.0
    - LGPL-2.0
component  : multimedia.library
summary    : D-Bus service for applications to request thumbnails
description: |
    The Tumbler package contains a D-Bus thumbnailing service based on the thumbnail management D-Bus specification. This is useful for generating thumbnail images of files.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(poppler-glib)
    - pkgconfig(libgsf-1)
setup      : |
    %configure \
        --disable-static \
        --disable-debug \
        --disable-gstreamer-thumbnailer
build      : |
    %make
install    : |
    %make_install
